// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250520215510_UpdateEntitiesWithPrimaryKeys")]
    partial class UpdateEntitiesWithPrimaryKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Alergia", b =>
                {
                    b.Property<int>("ID_Alergias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Alergias"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Alergia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Alergias");

                    b.ToTable("Alergias");
                });

            modelBuilder.Entity("backend.Models.Cita", b =>
                {
                    b.Property<int>("ID_Cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Cita"));

                    b.Property<int?>("EstatusCitaID_Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Cita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora_Cita")
                        .HasColumnType("time");

                    b.Property<int>("ID_Consultorio")
                        .HasColumnType("int");

                    b.Property<int>("ID_Estatus")
                        .HasColumnType("int");

                    b.Property<int>("ID_Medico")
                        .HasColumnType("int");

                    b.Property<int>("ID_Paciente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ultima_Actualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Cita");

                    b.HasIndex("EstatusCitaID_Estatus");

                    b.HasIndex("ID_Consultorio");

                    b.HasIndex("ID_Estatus");

                    b.HasIndex("ID_Medico");

                    b.HasIndex("ID_Paciente");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("backend.Models.Consultorio", b =>
                {
                    b.Property<int>("ID_Consultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Consultorio"));

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Consultorio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Consultorio");

                    b.HasIndex("ID_Estatus");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("backend.Models.Especialidad", b =>
                {
                    b.Property<int>("ID_Especialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Especialidad"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Especialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("backend.Models.EstatusCita", b =>
                {
                    b.Property<int>("ID_Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Estatus"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Estatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_Estatus");

                    b.ToTable("EstatusCitas");
                });

            modelBuilder.Entity("backend.Models.EstatusConsultorio", b =>
                {
                    b.Property<int>("ID_Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Estatus"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Estatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_Estatus");

                    b.ToTable("EstatusConsultorios");
                });

            modelBuilder.Entity("backend.Models.EstatusMedico", b =>
                {
                    b.Property<int>("ID_Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Estatus"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Estatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_Estatus");

                    b.ToTable("EstatusMedicos");
                });

            modelBuilder.Entity("backend.Models.EstatusPaciente", b =>
                {
                    b.Property<int>("ID_Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Estatus"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Estatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_Estatus");

                    b.ToTable("EstatusPacientes");
                });

            modelBuilder.Entity("backend.Models.EstatusUsuario", b =>
                {
                    b.Property<int>("ID_Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Estatus"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Estatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_Estatus");

                    b.ToTable("EstatusUsuarios");
                });

            modelBuilder.Entity("backend.Models.Genero", b =>
                {
                    b.Property<int>("ID_Generos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Generos"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero_Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Generos");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("backend.Models.Medico", b =>
                {
                    b.Property<int>("ID_Medico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Medico"));

                    b.Property<string>("Apellido_Materno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Apellido_Paterno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("EstatusMedicoID_Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Especialidad")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Medico");

                    b.HasIndex("EstatusMedicoID_Estatus");

                    b.HasIndex("ID_Especialidad");

                    b.HasIndex("ID_Estatus");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("backend.Models.Operacion", b =>
                {
                    b.Property<int>("ID_Operaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Operaciones"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Fecha_Operacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Operaciones");

                    b.ToTable("Operaciones");
                });

            modelBuilder.Entity("backend.Models.Paciente", b =>
                {
                    b.Property<int>("ID_Paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Paciente"));

                    b.Property<float?>("Altura")
                        .HasColumnType("real");

                    b.Property<string>("Apellido_Materno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Apellido_Paterno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CURP")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Calle")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Codigo_Postal")
                        .HasColumnType("int");

                    b.Property<string>("Correo_Electronico")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Alergias")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Genero")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Operaciones")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Padecimientos")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Num_Calle")
                        .HasColumnType("int");

                    b.Property<float?>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Paciente");

                    b.HasIndex("ID_Alergias");

                    b.HasIndex("ID_Estatus");

                    b.HasIndex("ID_Genero");

                    b.HasIndex("ID_Operaciones");

                    b.HasIndex("ID_Padecimientos");

                    b.HasIndex("ID_Tipo");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("backend.Models.Padecimiento", b =>
                {
                    b.Property<int>("ID_Padecimientos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Padecimientos"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Fecha_Diagnostico")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Padecimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Padecimientos");

                    b.ToTable("Padecimientos");
                });

            modelBuilder.Entity("backend.Models.PasswordRecoveryToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PasswordRecoveryTokens");
                });

            modelBuilder.Entity("backend.Models.Rol", b =>
                {
                    b.Property<int>("ID_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Rol"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("backend.Models.TipoSangre", b =>
                {
                    b.Property<int>("ID_Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Tipo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factor_RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Sangre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ID_Tipo");

                    b.ToTable("TiposSangre");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("Apellido_Materno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Apellido_Paterno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Correo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Estatus")
                        .HasColumnType("int");

                    b.Property<int>("ID_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Usuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("ID_Estatus");

                    b.HasIndex("ID_Rol");

                    b.HasIndex("Nombre_Usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Cita", b =>
                {
                    b.HasOne("backend.Models.EstatusCita", null)
                        .WithMany("Citas")
                        .HasForeignKey("EstatusCitaID_Estatus");

                    b.HasOne("backend.Models.Consultorio", "Consultorio")
                        .WithMany("Citas")
                        .HasForeignKey("ID_Consultorio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.EstatusCita", "EstatusCita")
                        .WithMany()
                        .HasForeignKey("ID_Estatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Medico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("ID_Medico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("ID_Paciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("EstatusCita");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("backend.Models.Consultorio", b =>
                {
                    b.HasOne("backend.Models.EstatusConsultorio", "EstatusConsultorio")
                        .WithMany("Consultorios")
                        .HasForeignKey("ID_Estatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstatusConsultorio");
                });

            modelBuilder.Entity("backend.Models.Medico", b =>
                {
                    b.HasOne("backend.Models.EstatusMedico", null)
                        .WithMany("Medicos")
                        .HasForeignKey("EstatusMedicoID_Estatus");

                    b.HasOne("backend.Models.Especialidad", "Especialidad")
                        .WithMany("Medicos")
                        .HasForeignKey("ID_Especialidad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.EstatusMedico", "EstatusMedico")
                        .WithMany()
                        .HasForeignKey("ID_Estatus")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especialidad");

                    b.Navigation("EstatusMedico");
                });

            modelBuilder.Entity("backend.Models.Paciente", b =>
                {
                    b.HasOne("backend.Models.Alergia", "Alergia")
                        .WithMany("Pacientes")
                        .HasForeignKey("ID_Alergias")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.EstatusPaciente", "EstatusPaciente")
                        .WithMany("Pacientes")
                        .HasForeignKey("ID_Estatus")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Genero", "Genero")
                        .WithMany("Pacientes")
                        .HasForeignKey("ID_Genero")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Operacion", "Operacion")
                        .WithMany("Pacientes")
                        .HasForeignKey("ID_Operaciones")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Padecimiento", "Padecimiento")
                        .WithMany("Pacientes")
                        .HasForeignKey("ID_Padecimientos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.TipoSangre", "TipoSangre")
                        .WithMany("Pacientes")
                        .HasForeignKey("ID_Tipo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Alergia");

                    b.Navigation("EstatusPaciente");

                    b.Navigation("Genero");

                    b.Navigation("Operacion");

                    b.Navigation("Padecimiento");

                    b.Navigation("TipoSangre");
                });

            modelBuilder.Entity("backend.Models.PasswordRecoveryToken", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.HasOne("backend.Models.EstatusUsuario", "EstatusUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("ID_Estatus")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("ID_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstatusUsuario");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("backend.Models.Alergia", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("backend.Models.Consultorio", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("backend.Models.Especialidad", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("backend.Models.EstatusCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("backend.Models.EstatusConsultorio", b =>
                {
                    b.Navigation("Consultorios");
                });

            modelBuilder.Entity("backend.Models.EstatusMedico", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("backend.Models.EstatusPaciente", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("backend.Models.EstatusUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Genero", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("backend.Models.Medico", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("backend.Models.Operacion", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("backend.Models.Paciente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("backend.Models.Padecimiento", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("backend.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.TipoSangre", b =>
                {
                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
